### ISSUE TITLE
Browsersync dependency version

### ISSUE THREAD

**Issue by arpie42** [ocombe/browser-sync-brunch#16]
Any chance of increasing the browsersync dependency version up to >2.6.0, to allow use of watch event callbacks, as documented here : https://browsersync.io/docs/options/#option-files
I've done this locally and it is working without issue (so far).

**Comment by ocombe** [comment]
Sure, if can you make a PR for that please?

**Comment by arpie42** [comment]
Of course : https://github.com/ocombe/browser-sync-brunch/pull/17
